export const bdInstitutions = [
  "Abdul Kadir Mollah City College",
  "Adamjee Cantonment College, Dhaka",
  "Adhyapak Abdul Majid College",
  "Aeronautical College of Bangladesh",
  "Aeronautical Institute of Bangladesh",
  "Agrabad Government Colony High School, Chittagong",
  "Agricultural University College, Mymensingh",
  "Agriculture Training Institute",
  "Ahammad Uddin Shah Shishu Niketon School & College",
  "Akkelpur High School",
  "Alekanda Govt College",
  "Alinagar Junior High School",
  "Amodpur High School",
  "Amrita Lal Dey College",
  "Ananda Mohan College",
  "Aranghata Junior High School",
  "Arani Junior High School",
  "Atomic Energy Research Establishment School and College",
  "Azam Khan Govt. Commerce College",
  "BAF Shaheen College Chattagram",
  "BAF Shaheen College Dhaka",
  "BAF Shaheen College Kurmitola",
  "BAF Shaheen College, Dhaka",
  "BCIC College",
  "BPATC School and College",
  "Bakalia Shahid N M M J Degree College",
  "Bangla College",
  "Bangladesh Institute of Glass and Ceramics",
  "Bangladesh Institute of Marine Technology",
  "Bangladesh International School and College",
  "Bangladesh Marine Academy",
  "Bangladesh Navy College Dhaka",
  "Bangladesh Sweden Polytechnic Institute",
  "Baraigram High School",
  "Barampur High School",
  "Barisal Cadet College",
  "Barisal Engineering College",
  "Barisal Government Women's College",
  "Barisal Polytechnic Institute",
  "Basudebpur High School",
  "Bausia Junior High School",
  "Belpukuria Junior High School",
  "Bhabanipur High School",
  "Bhandaria Government College",
  "Biam Model School and College Rajshahi",
  "Bijoy Smarani University College",
  "Billi High School",
  "Bir Uttam Shaheed Samad School & College",
  "Birshestha Munshi Abdur Rouf Public College",
  "Bogra Zilla School",
  "Brahmanbaria Government College",
  "Brajalal College",
  "Brindaban Government College",
  "Brojomohun College",
  "Cantonment Public School and College, Momenshahi",
  "Cantonment Public School and College, Rangpur",
  "Carmichael College",
  "Carmichael College, Rangpur",
  "Chabbishnagar High School",
  "Chandpur Junior High School",
  "Chandpur Polytechnic Institute",
  "Charfasson Govt. College",
  "Charghat Government High School",
  "Charghat High School",
  "Charmohanpur Junior High School",
  "Chittagong College",
  "Chittagong Collegiate School",
  "Chittagong Government High School",
  "Chittagong Grammar School",
  "Chittagong Ideal School & College",
  "Chittagong Model School and College",
  "Chittagong Pali College",
  "Chndrimaa Residential Area High School",
  "Chorkhoir High School",
  "Choto Lalpur Junior High School",
  "Chowmuhani Government S.A College",
  "College of Aviation & Technology",
  "College of Development Alternative",
  "Comilla Cadet College",
  "Comilla Government College",
  "Comilla Government Women's College",
  "Comilla Victoria Government College",
  "Cox's bazar government college",
  "Daffodil International College",
  "Dania College",
  "Dariapur Junior High School",
  "Daspara Junior High School",
  "Dhaka City College",
  "Dhaka College",
  "Dhaka Commerce College",
  "Dhaka Imperial College",
  "Dhaka Polytechnic Institute",
  "Dhaka Residential Model College",
  "Dhankoir High School",
  "Dhopapara High School",
  "Dinajpur Government College",
  "Dinajpur Polytechnique Institute",
  "Dinajpur Zilla School",
  "Dr. Khastagir Government Girls' High School",
  "Durgapur Junior High School",
  "Durgapur Pilot High School",
  "Eden Mohila College",
  "Engineering University School & College",
  "Faridpur Engineering College",
  "Faridpur Polytechnic Institute",
  "Faujdarhat Cadet College",
  "Feni Girls' Cadet College",
  "Feni Government College",
  "Feni Polytechnic Institute",
  "Gachbaria Govt. College",
  "Gazipur Cantonment College",
  "Ghoramara High School",
  "Godagari Pilot High School",
  "Godagari School and College",
  "Gogram High School",
  "Gole Afroz College",
  "Gopaldi Nazrul Islam Babu College",
  "Gopinathpur Junior High School",
  "Government Akbar Ali College",
  "Government Ashek Mahmud College",
  "Government Azizul Haque College",
  "Government Barisal College",
  "Government City College, Chittagong",
  "Government College of Commerce, Chittagong",
  "Government Debendra College",
  "Government Hazi Mohammad Mohshin College",
  "Government K. M. H. College",
  "Government K.C. College Jhenaidah",
  "Government Laboratory High School Rajshahi",
  "Government Laboratory High School, Dhaka",
  "Government P.C. College, Bagerhat",
  "Government Physical Education College, Dhaka",
  "Government Rajendra College",
  "Government Saadat College",
  "Government Science College, Dhaka",
  "Government Shaheed Suhrawardy College",
  "Government Titumir College",
  "Government Tolaram College",
  "Govt. Haraganga College",
  "Govt. Sheikh Fazilatunnesa Mujib Mohila College",
  "Gunabati College",
  "Gurudayal Government College",
  "Haji Abul Hossain Institute of Technology",
  "Haji Muhammad Mohsin College, Chittagong",
  "Hamdard Public College",
  "Haragach Junior High School",
  "Haragram Junior High School",
  "Haripur Junior High School",
  "Hathazari Government University College",
  "Hazera Taju University College",
  "Heyako Banani University College",
  "Holy Cross College, Dhaka",
  "Holy Cross Girls' High School",
  "Ibne Taimiya School and College",
  "Ideal College",
  "Ideal College, Dhanmondi",
  "Ideal School and College",
  "Ideal School and College, Motijheel",
  "Institute of Leather Engineering and Technology, University of Dhaka",
  "Ishwarganj Degree College",
  "Islamia Government College",
  "Ispahani Public School & College, Chittagong",
  "Ispahani Public School & College, Comilla",
  "Iswardi High School",
  "Jagotganj High School",
  "Jahangirpur Govt. College",
  "Jalalabad Cantonment Public School and College",
  "Jhenaidah Cadet College",
  "Joypurhat Girls' Cadet College",
  "Joypurhat Government College",
  "Kabi Nazrul Government College",
  "Kakonhat High School",
  "Kalma High School",
  "Kalma Junior High School",
  "Kamalpur Junior High School",
  "Kanpur Junior High School",
  "Karnaphuli Abdul Jalil Chowdhury College",
  "Kazla High School",
  "Khidirpur Junior High School",
  "Khulna Govt. Girls College",
  "Khulna Public College",
  "Kurigram Government College",
  "Kushtia Zilla School",
  "M. E. H. Arif College",
  "Madan Mohan College",
  "Madhupur College",
  "Madhupur Shahid Smrity Higher Secondary School",
  "Maizpara High School",
  "Mangalkot Junior High School",
  "Marizpur High School",
  "Masjid Mission Academy",
  "Mastermind School, Dhaka",
  "Maulana Mohammad Ali College",
  "Mirpur Bangla High School and College",
  "Mirpur Junior High School",
  "Mohammadpur Government College",
  "Mohammadpur Model School & College",
  "Mohammadpur Preparatory School & College",
  "Mohanpur Pilot High School",
  "Motihar High School",
  "Muminunnesa Women's College",
  "Mundumala Junior High School",
  "Murari Chand College",
  "Mymensingh Girls' Cadet College",
  "Mymensingh Polytechnic Institute",
  "Mymensingh Zilla School",
  "Nababpur High School",
  "Naogaon Government College",
  "Narail Victoria College",
  "Narayanganj Government Mohila College",
  "Narayanpur Junior High School",
  "Narinda Junior High School",
  "Nawab Faizunnesa Government College",
  "Nazipur Government College",
  "Nazirhat College",
  "New Government Degree College High School",
  "New Government Degree College, Rajshahi",
  "Noakhali Government College",
  "Noakhali Government Women's College",
  "Noakhali Science and Commerce School and College",
  "Noakhali Zilla School",
  "Notre Dame College, Dhaka",
  "Notre Dame College, Mymensingh",
  "Paba Pilot High School",
  "Pabna Cadet College",
  "Pabna Zilla School",
  "Pakri High School",
  "Pakundia Adarsha Mohila College",
  "Pakuria Junior High School",
  "Patuakhali Government College",
  "Perdana College of Malaysia",
  "Police Lines High School",
  "Police Lines School and College",
  "Polli Sree College",
  "Putia Pilot High School",
  "RAJUK Uttara Model College",
  "Rahmat Iqbal College",
  "Rajshahi Bagha High School",
  "Rajshahi Cadet College",
  "Rajshahi Cantonment School and College",
  "Rajshahi College",
  "Rajshahi Collegiate School",
  "Rajshahi Education Board Model School",
  "Rajshahi Government High School",
  "Rajshahi Govt City College School Section",
  "Rajshahi Govt Deaf and Blind School",
  "Rajshahi Metropolitan Police Lines Girls High School",
  "Rajshahi Model School and College",
  "Rajshahi Railway Junior High School",
  "Rajshahi Tech School and College",
  "Rajshahi University School",
  "Rajshahi Women's College School Section",
  "Rajuk Uttara Model College, Dhaka",
  "Ramnathpur High School",
  "Rangpur Cadet College",
  "Rangpur Engineering College",
  "Rangpur Government College",
  "Rangpur Public School And College",
  "Rangunia College",
  "Raozan Government University College",
  "Rishikul School",
  "Rohanpur Junior High School",
  "Royal Media College",
  "Rural Development Academy (Rda) School",
  "SOS Hermann Gmeiner College",
  "Safiuddin Sarker Academy and College",
  "Saidpur College",
  "Sapahar Government College",
  "Sapura High School",
  "Sardah Junior High School",
  "Sarnagar High School",
  "Satkania Government College, Chittagong",
  "Scholastica, Dhaka",
  "Shaheed Abdur Rab Serniabat Textile Engineering College",
  "Shaheed Bir Uttam Lt. Anwar Girls' College",
  "Shaheed Police Smrity College",
  "Shaheed Ramiz Uddin Cantonment College",
  "Shaheed Smriti Govt High School",
  "Shaheed Smriti High School",
  "Shahid A.H.M. Kamaruzzaman Govt. Degree College",
  "Shahid Buddhijibi Government College",
  "Shahid Syed Nazrul Islam College",
  "Shahidul Chowdhury Engineering College",
  "Shahjadpur Junior High School",
  "Shaikh Burhanuddin Post Graduate College",
  "Sherpur Government College",
  "Shibnagar Junior High School",
  "Shyamoli Textile Engineering College",
  "Sonapur Degree College",
  "Sristy Academic school/ Sristy College of Tangail",
  "St. Gregory's High School and College",
  "St. Joseph Higher Secondary School, Dhaka",
  "Sujanagar High School",
  "Sylhet Cadet College",
  "Sylhet Engineering College",
  "Sylhet Government Pilot High School",
  "Sylhet Government Women's College",
  "Sylhet MC College",
  "Sylhet Science And Technology College",
  "Talaimari High School",
  "Tangail Polytechnic Institute",
  "Tanore Pilot High School",
  "Tejgaon College",
  "Tejgaon Mohila College",
  "Terokhadia Junior High School",
  "Tetulia B. M. C. College",
  "Textile Engineering College, Chittagong",
  "Thakurgaon Government College",
  "Ullapara Science College",
  "United College of Aviation, Science & Management",
  "University Laboratory School and College",
  "Upasahar Girls High School",
  "Uttar Kattoli Alhaz Mostafa Hakim University College",
  "Uttara Government College",
  "Uttara Town College",
  "Viquarunnisa Noon School and College, Dhaka",
  "Willes Little Flower School and College",
  "Zinnatpur Junior High School",
];
